LST = [1,2,3,4,5]
for no in lst:
    print(no)

    # 1~100 반복 range(1,101)
    # 조건 5의 배수

range(1,101)

for i in range(1,101):
if i % 5 = 0:
    print(i)

treehit = 0
while treehit<10 :
    treehit += 1
    # 나무를 찍는 횟수를 1씩 증가
    print("찍은횟수:",treehit)
    if treehit == 10
        print("미션완료")

treehit = 0
for treehit in range(1,101):
    treehit +=1
    print("찍은횟수:",treehit)
    if treehit ==10
        print("미션완료")

# while문 일정한 범위까지만 반복, for의 경우 기간동안 계속 반복---- 뭔 차이지?