# 문자열의 특징

oneline = "this is one line string"
print(oneline)

# 줄내림 1
multiline = """this is
multi line 
string"""

# 줄내림 2
multiline2 = "this is \nmulti line \nstring"

# find 찾는 문자열이 처음 나온 위치 반환, 없을시는 -1
#
# print( multiline2,find('m'))
# print( multiline2[8:13])

# # 문자열 바꾸기 - replce
#
# str2 = " i like apple"
# print(str2, replace("apple","i like banana"))
#
# # split - 구분자
# str3 = "사과/자몽/바나나"
# print( str3. split('/'))

